/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface RatingImageGenerator {
    'rating': number;
    'scale': number;
    'starSize': number;
  }
  interface RatingImageGeneratorAttributes extends StencilHTMLAttributes {
    'rating'?: number;
    'scale'?: number;
    'starSize'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'RatingImageGenerator': Components.RatingImageGenerator;
  }

  interface StencilIntrinsicElements {
    'rating-image-generator': Components.RatingImageGeneratorAttributes;
  }


  interface HTMLRatingImageGeneratorElement extends Components.RatingImageGenerator, HTMLStencilElement {}
  var HTMLRatingImageGeneratorElement: {
    prototype: HTMLRatingImageGeneratorElement;
    new (): HTMLRatingImageGeneratorElement;
  };

  interface HTMLElementTagNameMap {
    'rating-image-generator': HTMLRatingImageGeneratorElement
  }

  interface ElementTagNameMap {
    'rating-image-generator': HTMLRatingImageGeneratorElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
