/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface RatingImage {
    'rating': number;
    'scale': number;
    'starSize': number;
  }
  interface RatingImageAttributes extends StencilHTMLAttributes {
    'rating'?: number;
    'scale'?: number;
    'starSize'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'RatingImage': Components.RatingImage;
  }

  interface StencilIntrinsicElements {
    'rating-image': Components.RatingImageAttributes;
  }


  interface HTMLRatingImageElement extends Components.RatingImage, HTMLStencilElement {}
  var HTMLRatingImageElement: {
    prototype: HTMLRatingImageElement;
    new (): HTMLRatingImageElement;
  };

  interface HTMLElementTagNameMap {
    'rating-image': HTMLRatingImageElement
  }

  interface ElementTagNameMap {
    'rating-image': HTMLRatingImageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
